version: "3.9"

services:
  mlserviceziwg:
    container_name: mlserviceziwg
    volumes:
      - ./workspace:/workspace
    build:
      context: .
    ipc: "host"
    stdin_open: true
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]